-- Active: 1709824304208@@127.0.0.1@3306@org
SHOW DATABASES;
USE ORG;

CREATE TABLE Worker (
    WORKER_ID INT NULL PRIMARY KEY AUTO_INCREMENT ,
    FIRST_NAME VARCHAR(25) ,
    LAST NAME VARCHAR(25) ,
    SALARY INT(15) ,
    JOINING_DATE DATETIME , 
    DEPARTMENT VARCHAR(25)
);

INSERT INTO Worker
    VALUES(WORKER_ID , FIRST_NAME , LAST_NAME , SALARY , JOINING_DATE , DEPARTMENT)
    